# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kio': '@stable'
    'pim/akonadi' : '@stable'
    'pim/akonadi-contacts' : '@stable'
    'pim/kmime' : '@stable'
